// Generated by CoffeeScript 1.9.3
(function() {
  var cwd, path;

  path = require('path');

  cwd = process.cwd();

  module.exports = {
    entry: path.join(cwd, 'assets/scripts/main.coffee'),
    output: {
      path: cwd,
      filename: 'bundle.js'
    },
    module: {
      loaders: [
        {
          test: /\.coffee$/,
          loader: "coffee"
        }
      ]
    }
  };

}).call(this);
